### ISSUE TITLE
Lightning Aspect ID is misspelled

### ISSUE THREAD

**Issue by anticode-403** [Provismet/Extended-Enchanting#3]
### Type of Error

Other

### Description

`extended-enchantments:lighting_aspect` is meant to be `extended-enchantments:lightning_aspect`

### Mod Version

1.0.0

### Minecraft Version

1.20.1

### Mod Loader

Fabric

### Steps to Reproduce

what do you want from me you just misspelled it

**Comment by Provismet** [comment]
Fixed as of 1.0.1+1.20.1 and 1.0.3+1.20.6 versions.
